In [ ]:
from utils.buffers import SimpleBuffer
from algos.CrossQ import CrossQSAC_Agent

import gymnasium as gym

my_buffer = SimpleBuffer(10, 2, gamma=0.99, n_steps=1)
my_env = gym.make("Pendulum-v1")
my_agent = CrossQSAC_Agent(my_env, replay_buffer=my_buffer, use_wandb=False)
my_agent._do_random_actions(1)
print(my_buffer)

state: [-0.98057216  0.19615878  0.1533995 ], action: [-1.8872153], reward: -8.673955136877085, next_state: [-0.9807428   0.19530383  0.0174363 ], terminated: False, truncated: False, info: {}
state: [-0.9807428   0.19530383  0.0174363 ], action: [-1.8872153], reward: -8.676766671973006, next_state: [-0.9795617   0.201144   -0.11916812], terminated: False, truncated: False, info: {}
state: [-0.9795617   0.201144   -0.11916812], action: [-1.8872153], reward: -8.643096562448367, next_state: [-0.97695607  0.2134405  -0.25139242], terminated: False, truncated: False, info: {}
state: [-0.97695607  0.2134405  -0.25139242], action: [-1.8872153], reward: -8.574268354227934, next_state: [-0.9727896   0.23169038 -0.37439433], terminated: False, truncated: False, info: {}
state: [-0.9727896   0.23169038 -0.37439433], action: [-1.8872153], reward: -8.472749677538495, next_state: [-0.9669021   0.25514767 -0.48370883], terminated: False, truncated: False, info: {}
state: [-0.9669021   0.25514767 -0.

In [12]:
samples = my_buffer.sample(3)

In [13]:
samples[0]

array([[-0.9396295 ,  0.34219354,  0.7158265 ],
       [-0.9602625 ,  0.27909857,  0.63851327],
       [-0.8832996 ,  0.468809  ,  0.578415  ]], dtype=float32)

In [14]:
samples[1]

array([[-1.8872153],
       [-1.8872153],
       [-1.8872153]], dtype=float32)

In [15]:
samples[2]

array([-7.85197766, -8.216711  , -7.07888004])

In [16]:
samples[3]

array([[-0.95086426,  0.30960816,  0.6893894 ],
       [-0.9677597 ,  0.25187528,  0.5647549 ],
       [-0.8979994 ,  0.4399967 ,  0.64693946]], dtype=float32)

In [17]:
samples[4]

array([False, False, False])

In [18]:
samples[5]

array([False, False, False])

In [ ]:
import numpy as np
np.array(my_buffer.sample(3)[2])

array([[-1.8872153],
       [-1.8872153],
       [-1.8872153]], dtype=float32)